### ISSUE TITLE
Properly list usernames when performing an action command

### ISSUE THREAD

**Issue by maxhoesel** [PhunStyle/FurBot#57]
Right now, performing an action such as `f.hug` with multiple mentions will result in the bot inserting an 'and' between each user. While this works fine for 2 mentions max, it becomes rather unpleasing when more users are mentioned. 

Here's an example of what I'm talking about:
Command:
`f.hug user1 user2 user3 user4`

Current output:
`$me gives user1 and user2 and user3 and user4 a warm hug`

Desired output:
`$me gives user1, user2, user3 and user4 a warm hug`

I prefer this format as it is shorter and easier to read (and also grammatically correct). 

Implementing this will probably require replacing the recieverArray.join() call in every action function with something a little more elaborate. The best idea i could come up with is to iterate through the recieverArray, appending each username to the receivers string one by one with an ", ", until the last one is added with " and " instead. There might be a more elegant way to do this in JS though, I'm not too familiar with the language :)

Cheers

**Comment by PhunStyle** [comment]
Since i didn't comment anything yet and kinda felt bad not leaving you with any message;

I absolutely agree that a comma separated list for more than 2 people was the right call. Thanks for the suggestion, it looks way better this way :)!

**Comment by maxhoesel** [comment]
Thanks for implementing this so quickly! I figured that it was probably just an oversight -glad to hear that you like it better as well ^^
