### ISSUE TITLE
Blacklist not working

### ISSUE THREAD

**Issue by RoseWoodKitty** [PhunStyle/FurBot#74]
All commands other than f.blacklist get and f.blacklist are not working correctly.
We cannot add or set any tags into the black list by any means and f.blacklist get just shows us an empty list

**Comment by PhunStyle** [comment]
Hi @RoseWoodKitty Thanks for submitting an issue in our GitHub!

We're currently working on a complete re-write of the bot with an updated library, some features on the current code are severely outdated.

You can track the progress in the FurBot discord server in the announcements channel, if you don't want to join that's fine too; i've attached a screenshot of the most recent announcements so you can see what is currently broken. We're trying to get the rewrite out as soon as possible.
![image](https://user-images.githubusercontent.com/6770468/100801941-fcd3b080-3428-11eb-95a6-604dc1e91648.png)
![image](https://user-images.githubusercontent.com/6770468/100801963-052beb80-3429-11eb-8725-31cbdcf7e865.png)
