### ISSUE TITLE
Furbot offline in my server but is online in a different server

### ISSUE THREAD

**Issue by TheBrockReal** [PhunStyle/FurBot#76]
For some reason Furbot has been offline in my server ever since sometime in February and still is offline.
But in a different server, It's online as well as the bot's DMs i can use the commands. 
Here's proof
![Screenshot_20220302-065802_Discord](https://user-images.githubusercontent.com/81770173/156357553-e45edb4e-8600-4e00-91bd-6a3f72fc2bbc.jpg)
![Screenshot_20220302-065812_Discord](https://user-images.githubusercontent.com/81770173/156357557-4a561a87-1fc6-4b7d-9401-654dc7e819e2.jpg)
![Screenshot_20220302-065826_Discord](https://user-images.githubusercontent.com/81770173/156357559-e25c8629-8c78-4c74-8a2f-aa080e986fa2.jpg)
![Screenshot_20220302-065840_Discord](https://user-images.githubusercontent.com/81770173/156357560-f40bf1c0-5c2c-44f8-b1a1-1fb8056ce89d.jpg)

**Comment by Gideon-Foxo** [comment]
The bot has basically been shut down at this point, sorry :c

**Comment by benjigh** [comment]
> The bot has basically been shut down at this point, sorry :c

Is there any plan to get it back online ?

**Comment by PhunStyle** [comment]
> For some reason Furbot has been offline in my server ever since sometime in February and still is offline. But in a different server, It's online as well as the bot's DMs i can use the commands. 

Might be because the bot had an issue or ran out of space in the shard -- i've rebooted it so check if it still happens, otherwise i might need to up the amount of shards again (which i probably already should've done).

**Comment by PhunStyle** [comment]
> > The bot has basically been shut down at this point, sorry :c
> 
> Is there any plan to get it back online ?

The current version can stay online for as long as the discord api protocol will allow me to, otherwise it either needs to shut down or there needs to be a v2 built somehow. (more details can be found on the main page of this repository which i have updated).
